# Site settings
title: "Visualization in Data Science (VDS at ACM KDD 2021)"
email: "vds@ieeevis.org"
description: "Visualization in Data Science (VDS at ACM KDD 2021)"
baseurl: "/2021"
url: "http://www.visualdatascience.org/"
conferenceshort: "VDS 2021"
conferencedate: "August 14-18th, 2021" #"Mon, Oct. 26, 2020"

deadline_submission: "May 20th, 2021" # <s>Fri, July 17, 2020</s><br> Fri, July 24, 2020"
deadline_notification: "June 10th, 2021" #"<s>Fri, August 28, 2020</s><br> Fri, Sept. 4, 2020"
event_date: "August 14-18th, 2021 (virtual)" #"Mon, Oct. 26, 2020"
event2_date: "October 24-29th, 2021 (virtual)"

# Build settings
markdown: kramdown

collections:
- talks

